import Database from "better-sqlite3";
import { drizzle, type BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { DB_PATH } from "@/lib/paths";
import * as schema from "./schema";

export type Db = BetterSQLite3Database<typeof schema>;

const globalForDb = globalThis as unknown as { __communityDb?: Db; __communitySqlite?: Database.Database };

/**
 * Process-wide DB handle. Next dev re-evaluates modules on HMR, so we park it on globalThis.
 * Migrations (generated by drizzle-kit into ./drizzle) run once on first open.
 */
export function getDb(): Db {
  if (globalForDb.__communityDb) return globalForDb.__communityDb;
  mkdirSync(dirname(DB_PATH), { recursive: true });
  const sqlite = new Database(DB_PATH);
  sqlite.pragma("journal_mode = WAL");
  sqlite.pragma("synchronous = NORMAL");
  sqlite.pragma("foreign_keys = ON");
  const db = drizzle(sqlite, { schema });
  migrate(db, { migrationsFolder: resolve(process.cwd(), "drizzle") });
  globalForDb.__communityDb = db;
  globalForDb.__communitySqlite = sqlite;
  return db;
}

/** Raw handle for hot paths (bulk inserts with prepared statements). */
export function getSqlite(): Database.Database {
  getDb();
  return globalForDb.__communitySqlite!;
}
